Sorting/java/Swap_count_bs.cpp
=> Swap_count_bs.cpp

Misc/DayOfDate.cpp, Misc/nextPalin.cpp
Two of the most popular questions asked in Coding Rounds of Samsung and Microsoft.
=> nextPalin and DayOfDate

BinaryTrees/MorrisTraversal.cpp
Added the most famous Binary Tree traversal algorithm asked in interviews which does traversal of Tree in O(1) space without requiring stack and recursion.
=> added morrisTraversal

Divide_and_Conquer/binary_search.py, Divide_and_Conquer/maximum-subarray.py, Greedy_Algorithm/money_change_problem.py
Added greedy algorithm and Divide_and_conquer Algorithms
=> Added Greedy and Divide&conquer Algo

Misc/Pair.java
User can import the file to use Pair in Java as they use it in C++
=> Added C++ alternative of Pair in Java

BITApplication
Number of elements less than or equal to a given number in a given subarray
using BIT
=> BITApplication.cpp

Algorithms/FenwickTree.java
Added BIT tree or Fenwick Tree for faster range sum queries in Java.
=> Added code for Fenwick tree in Java

Divide_and_Conquer/Matrix_chain_multiplication.py, Searching/Linear_search.py, Searching/binary_search.py, Sorting/python/Insertion_sort.py, Sorting/python/Randomized_quick_sort.py, Sorting/python/Selection_sort.py
Added Insertion sort, selection sort , randomized quick sort, MCM ( Divide and Conquer) , binary Search and linear Search algorithms
=> Added Algorithms

Searching/Linear_Search.cpp, Stacks/queue_to_stack.cpp
Implementation os Queue using 2 Stacks
=> Implementation os Queue using 2 Stacks

Stacks/StackImplementUsingVector.cpp
=> Added stack via vector

DP/CoinExchange.java
The following program illustrates optimised DP approach to solve the following problem.
-Given k coins, find the number of ways to pay n amount.
=> CoinExchange.java

Sorting/bubblesort.cpp
Simple Program to sort elements using bubble sorting.
=> Created bubblesort.cpp

Graphs/bfs.cpp
Breadth First Search or BFS for a Graph
=> Breadth First Search or BFS for a Graph

Heap/heap.cpp
we simply build Max Heap without caring about the input. We start from bottom-most and rightmost internal mode of min Heap and heapify all internal modes in bottom up way to build the Max heap.
=> A C++ program to convert min Heap to max Heap

Graphs/Topological_Sort.cpp
Topological sorting for Directed Acyclic Graph (DAG) is a linear ordering of vertices such that for every directed edge uv, vertex u comes before v in the ordering. Topological Sorting for a graph is not possible if the graph is not a DAG.
=> Topological_Sort.cpp

Graphs/floyd_warshall.cpp
This algorithm gives shortest distance between each pair of nodes.
=> floyd_warshall.cpp

Graphs/Dijkstra_Sort.cpp
Given a graph and a source vertex in the graph, find shortest paths from source to all vertices in the given graph.
=> Dijkstra_Sort.cpp

DP/rod_cutting.cpp
This algorithm gives the maximum value obtainable for the given rod.
=> rod_cutting.cpp

DP/binary_knapsack.cpp
Given weights and values of n items, put these items in a knapsack of capacity W to get the maximum total value in the knapsack.
=> binary_knapsack.cpp

LinkedList/Linked_list.cpp
Find length of loop in linked list
=> Find length of loop in linked list

Graphs/mother_vertex.cpp
A mother vertex in a graph G = (V,E) is a vertex v such that all other vertices in G can be reached by a path from v.
=> mother_vertex.cpp

Graphs/transpose_graph.cpp
Transpose of a directed graph G is another directed graph on the same set of vertices with all of the edges reversed compared to the orientation of the corresponding edges in G. That is, if G contains an edge (u, v) then the converse/transpose/reverse of G contains an edge (v, u) and vice versa.
=> transpose_graph.cpp

DP/MaxSumseq.cpp
Given an array of n positive integers. Write a program to find the sum of maximum sum subsequence of the given array such that the integers in the subsequence are sorted in increasing order. For example, if input is {1, 101, 2, 3, 100, 4, 5}, then output should be 106 (1 + 2 + 3 + 100), if the input array is {3, 4, 5, 10}, then output should be 22 (3 + 4 + 5 + 10) and if the input array is {10, 5, 4, 3}, then output should be 10
=> MaxSumseq.cpp

DP/Mat_Chain_Multi.cpp
Given a sequence of matrices, find the most efficient way to multiply these matrices together. The problem is not actually to perform the multiplications, but merely to decide in which order to perform the multiplications.
=> Mat_Chain_Multi.cpp

LinkedList/LRUCache.cpp
Added code for LRU Cache along with explanation.
=> Added LRU Cache Code

LinkedList/CircularLinkedList.java
Added code for circular linked list
=> Added CircularLinkedList using Java

Misc/HashMapImplementation.cpp
C++ code for HashMap implementation generally asked in interviews.
=> Added HashMap implementation in C++

Graphs/LCA_deepestleaves.cpp
=> added lca algorithm for graph
